project:
  type: website

website:
  title: "Wei Peng's Analytics Journey"
  navbar:
    left:
    - text: "RStudio"
      menu:
        - text: "Analyzing Bus Traffic Flows in Singapore"
          href: "RStudio/Geospatial_Analytics/Analyzing_Bus_Traffic_Flows/Analyzing_Bus_Traffic_Flows.qmd"
    
        - text: "Creating Better Visualisations"
          href: "RStudio/Visual_Analytics/Creating_Better_Visualisations/Creating_Better_Visualisations.qmd"
          
        - text: "Unveiling spatial and spatio-temporal mobility patterns"
          href: "RStudio/Geospatial_Analytics/Unveiling_spatio_temporal_mobility_patterns/Unveiling_spatio_temporal_mobility_patterns.qmd"
   
    - text: "Tableau"
      menu:
        - text: "Quarterly Private Residential Property Watcher"
          href: "Tableau/Quarterly_Private_Residential_Property_Watcher.qmd"
        
        - text: "Mapping In Tableau"
          href: "Tableau/Mapping_In_Tableau.qmd"
          
        - text: "Bullet Graph and Sparkline"
          href: "Tableau/Bullet_Graph_and_Sparkline.qmd"

    - text: "Python"
      menu:
        - text: "Image Learning on CIFAR-10"
          href: "Python/ImageLearningCifar10.qmd"
          
        - text: "AutoML for Binary Classification"
          href: "Python/AutoML_Binary_Classification.qmd"
        
    right:
      - href: index.qmd
        text: Home
      - icon: linkedin
        href: https://www.linkedin.com/in/weipengten
        aria-label: Linkedin
      - icon: github
        href: https://github.com/weipengten
        aria-label: Github
  page-footer:
    background: light
    left: 
      - href: https://quarto.org/
        text: "Published with Quarto |"
      - href: https://www.netlify.com/
        text: "Hosted by Netlify"


format:
  html:
    theme: sandstone
    toc: true
    toc-title: "On this page"
    toc-expand: 3
    toc-depth: 3
    css: styles.css
    
editor: visual

