project:
  type: website

website:
  title: "Wei Peng's Analytics Journey"
  navbar:
    left:
    - text: "Geospatial Analytics"
      menu:
        - text: "Analyzing Bus Traffic Flows in Singapore"
          href: "Geospatial_Analytics/Analyzing_Bus_Traffic_Flows/Take-Home_Ex02.qmd"
    - text: "Visual Analytics"
      menu:
        - text: "Creating Better Visualisations"
          href: "Visual_Analytics/Creating_Better_Visualisations/Take-Home_Ex02.qmd"
    right:
      - href: Main.qmd
        text: Home


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-title: "On this page"
    number-sections: true
    toc-expand: 3
    toc-depth: 3
    
editor: visual

