project:
  type: website

website:
  title: "Wei Peng's Analytics Journey"
  navbar:
    left:
    - text: "Geospatial Analytics"
      menu:
        - text: "Analyzing Bus Traffic Flows in Singapore"
          href: "Geospatial_Analytics/Take-Home_Ex2/Take-Home_Ex2.qmd"
    - text: "Visual Analytics"
      menu:
        - text: "Creating Better Visualisations"
          href: "Visual_Analytics/Take-Home_Ex2/Take-Home_Ex2.qmd"
    right:
      - href: Main.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true

editor: visual


