project:
  type: website

website:
  title: "Wei Peng's Analytics Journey"
  navbar:
    left:
    - text: "Geospatial Analytics"
      menu:
        - text: "Analyzing Bus Traffic Flows in Singapore"
          href: "Geospatial_Analytics/Analyzing_Bus_Traffic_Flows/Analyzing_Bus_Traffic_Flows.qmd"
    - text: "Visual Analytics"
      menu:
        - text: "Creating Better Visualisations"
          href: "Visual_Analytics/Creating_Better_Visualisations/Creating_Better_Visualisations.qmd"
    right:
      - href: index.qmd
        text: Home
  page-footer:
    background: light
    left: 
      - href: https://quarto.org/
        text: "Published with Quarto |"
      - href: https://www.netlify.com/
        text: "Hosted by Netlify"


format:
  html:
    theme: sandstone
    toc: true
    toc-title: "On this page"
    number-sections: true
    toc-expand: 3
    toc-depth: 3
    
editor: visual

